server:
  port: 28853

trip:
  yandexapikey:

jwt:
  secret: VERY_SECRET_PHRASE_OOOF
  refresh_secret: VERY_SECRET_PHRASE_FOR_REFRESH_TOKEN_OOOF

spring:
  data:
    mongodb:
      database: mongo-container
      #host: mongo-container
      host: localhost
      port: 27017

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: postgres

  datasource:
    url: jdbc:postgresql://localhost:5432/postgresDB
    #url: jdbc:postgresql://postgres-container:5432/postgresDB
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

logging:
  level:
    org:
      springframework:
        security: DEBUG

