server:
  port: 28853

trip:
  yandexapikey:

jwt:
  secret: VERY_SECRET_PHRASE_OOOF
  refresh_secret: VERY_SECRET_PHRASE_FOR_REFRESH_TOKEN_OOOF


spring:
  data:
    mongodb:
      database: testMDB
      username: mongo
      password: mongo
      uri: mongodb://mongo:mongo@localhost:27017/testMDB

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  sql:
    init:
      platform: postgres

  datasource:
    url: jdbc:postgresql://localhost:5432/testPG
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

logging:
  level:
    org:
      springframework:
        security: DEBUG

